export const FETCH_PLACEMARKS_REQUEST = "@@map/FETCH_PLACEMARKS_REQUEST";
export const FETCH_PLACEMARKS_SUCCESS = "@@map/FETCH_PLACEMARKS_SUCCESS";
export const FETCH_PLACEMARKS_ERROR = "@@map/FETCH_PLACEMARKS_ERROR";

export const ADD_PlACEMARK = "@@map/ADD_PlACEMARK";
export const ADD_PlACEMARK_IN_LIST = "@@map/ADD_PlACEMARK_IN_LIST";
export const ADD_COORDINATES = "@@map/ADD_COORDINATES";
